services:
  - type: web
    name: taimili-villa-bot
    env: python
    region: singapore
    plan: free
    runtime: python-3.9.16
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: "8080"
